name: TownyWarps
version: '1.0'
main: org.breakthebot.TownyWarps.TownyWarps
api-version: '1.21'
authors: [ charisk, Veyronity ]
permissions:
  townywarps.warp.use:
    description: Allows teleporting to warps, listing warps, and fetching warp info
    default: true
  townywarps.warp.create:
    description: Allows creating warps (Mayor only)
    default: op
  townywarps.warp.delete:
    description: Allows deleting warps (Mayor only)
    default: op
  townywarps.warp.level:
    description: Allows changing warp access level (Mayor only)
    default: op

dependencies:
  - name: Towny
    required: true
