name: TownyWarp
version: '1.0-SNAPSHOT'
main: org.breakthebot.townyWarp.TownyWarp
api-version: '1.21'
authors: [ charisk ]
permissions:
  townwarps.warp.use:
    description: Allows using town warps
    default: true
  townwarps.warp.create:
    description: Allows creating warps (Mayor only)
    default: op
  townwarps.warp.delete:
    description: Allows deleting warps (Mayor only)
    default: op
  townwarps.warp.level:
    description: Allows changing warp access level (Mayor only)
    default: op
  townwarps.warp.toggle:
    description: Toggle warp enable/disable (Mayor only)
    default: op
